//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ODID { get; set; }
        public Nullable<int> OrderQty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Net { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> OID { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
